### ISSUE TITLE
SparseMatMatComputation

### ISSUE THREAD

**Issue by darshansarojini** [LSDOlab/csdl_om#2]
Modify the code to allow this operation to not fail if zeros are in the matrix
https://github.com/LSDOlab/csdl_om/blob/master/csdl_om/comps/sparsemat_mat_comp.py#L34

A_data = self.sparse_mat[self.sparse_mat.nonzero()]

**Comment by darshansarojini** [comment]
`
import csdl
from csdl_om import Simulator

import numpy as np
from scipy.sparse import coo_array


class Model(csdl.Model):

    def define(self):
        mat = np.ones([4, 4])
        mat1 = self.create_input(name='matrix', val=mat)

        row = np.array([0, 3, 1, 0])
        col = np.array([0, 3, 1, 2])
        data2 = np.array([1., 2., 0., 12.])
        mat2 = coo_array((data2, (row, col)), shape=(4, 4)).tocsc()

        actuating_points = csdl.sparsematmat(mat1, sparse_mat=mat2)

        out = self.register_output(name='out', var=actuating_points)
        self.print_var(var=out)


if __name__ == "__main__":
    model = Model()
    sim = Simulator(model)
    sim.run()
    sim.visualize_implementation()
`

**Comment by afletche** [comment]
Lines 32-36 in the sparsemat_mat component:
# Y = AX
# [ik] = [ij][jk]
# A_data = self.sparse_mat.   # OLD Line
A_rows, A_cols = self.sparse_mat.
A_data = self.sparse_mat[self.sparse_mat.nonzero()]    # New Line

**Comment by vgucsd** [comment]
Fixed
